/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new tenant + owner user.
         *     Creates: Tenant → User (role=tenant_admin) → free Subscription → tokens.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email + password. Returns token pair.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate refresh token — validates old, issues new pair, revokes old.
         *     Reuse of a revoked refresh token should trigger all sessions to be invalidated.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke a specific refresh token (logout from one device).
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current authenticated user's profile.
         */
        get: operations["me_api_v1_auth_me_get"];
        /**
         * Update Profile
         * @description Update the current user's profile.
         */
        put: operations["update_profile_api_v1_auth_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charts/natal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Natal Chart
         * @description Generate a KP natal chart. Stores full chart data as JSONB.
         */
        post: operations["create_natal_chart_api_v1_charts_natal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charts/horary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Horary Chart
         * @description Generate a KP horary chart from a number (1–249).
         */
        post: operations["create_horary_chart_api_v1_charts_horary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Charts
         * @description List all charts for the current tenant (paginated).
         */
        get: operations["list_charts_api_v1_charts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charts/{chart_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chart
         * @description Retrieve a specific chart by ID.
         */
        get: operations["get_chart_api_v1_charts__chart_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chart
         * @description Soft-delete a chart.
         */
        delete: operations["delete_chart_api_v1_charts__chart_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clients
         * @description List clients for the current tenant with optional search and sorting.
         */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        /**
         * Create Client
         * @description Create a new client record.
         */
        post: operations["create_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client
         * @description Get a single client by ID.
         */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Client
         * @description Soft-delete a client.
         */
        delete: operations["delete_client_api_v1_clients__client_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Client
         * @description Update client fields.
         */
        patch: operations["update_client_api_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/clients/{client_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client Chart
         * @description Return the most recent natal chart for a client.
         */
        get: operations["get_client_chart_api_v1_clients__client_id__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChartCreateRequest
         * @description Request body for creating a natal chart.
         */
        ChartCreateRequest: {
            /** Birth Name */
            birth_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Birth Time
             * Format: time
             */
            birth_time: string;
            /**
             * Birth Tz
             * @description IANA timezone string, e.g. 'Asia/Kolkata'
             */
            birth_tz: string;
            /**
             * Birth Lat
             * @description Latitude in decimal degrees
             */
            birth_lat: number;
            /**
             * Birth Lon
             * @description Longitude in decimal degrees
             */
            birth_lon: number;
            /** Birth Location Name */
            birth_location_name?: string | null;
            /** Client Id */
            client_id?: string | null;
            /**
             * Ayanamsa
             * @description Ayanamsa: KP | Lahiri | Raman
             * @default KP
             */
            ayanamsa: string;
            /**
             * House System
             * @description House system: Placidus | Koch | Equal
             * @default Placidus
             */
            house_system: string;
        };
        /**
         * ChartListItem
         * @description Lightweight chart summary for list views.
         */
        ChartListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Chart Type */
            chart_type: string;
            /** Birth Name */
            birth_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Birth Location Name */
            birth_location_name: string | null;
            /** Calculated At */
            calculated_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Client Id */
            client_id: string | null;
        };
        /**
         * ChartOut
         * @description Chart response — includes full computed data.
         */
        ChartOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Chart Type */
            chart_type: string;
            /** Birth Name */
            birth_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Birth Time
             * Format: time
             */
            birth_time: string;
            /** Birth Tz */
            birth_tz: string;
            /** Birth Lat */
            birth_lat: number;
            /** Birth Lon */
            birth_lon: number;
            /** Birth Location Name */
            birth_location_name: string | null;
            /** Ayanamsa */
            ayanamsa: string;
            /** House System */
            house_system: string;
            /** Chart Data */
            chart_data: {
                [key: string]: unknown;
            } | null;
            /** Engine Version */
            engine_version: string | null;
            /** Calculated At */
            calculated_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Client Id */
            client_id: string | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Gender
             * @default male
             */
            gender: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /**
             * Time Of Birth
             * Format: time
             */
            time_of_birth: string;
            /** Place Of Birth */
            place_of_birth: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Timezone */
            timezone: string;
            /** Notes */
            notes?: string | null;
        };
        /** ClientListItem */
        ClientListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Gender */
            gender: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Place Of Birth */
            place_of_birth: string;
            /** Lagna Sign */
            lagna_sign?: string | null;
            /** Current Dasha */
            current_dasha?: string | null;
            /** Natal Chart Id */
            natal_chart_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClientListResponse */
        ClientListResponse: {
            /** Items */
            items: components["schemas"]["ClientListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has More */
            has_more: boolean;
        };
        /** ClientOut */
        ClientOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Full Name */
            full_name: string;
            /** Gender */
            gender: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /**
             * Time Of Birth
             * Format: time
             */
            time_of_birth: string;
            /** Place Of Birth */
            place_of_birth: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Timezone */
            timezone: string;
            /** Lagna Sign */
            lagna_sign?: string | null;
            /** Lagna Degree */
            lagna_degree?: number | null;
            /** Current Dasha */
            current_dasha?: string | null;
            /** Natal Chart Id */
            natal_chart_id?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Gender */
            gender?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Time Of Birth */
            time_of_birth?: string | null;
            /** Place Of Birth */
            place_of_birth?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Timezone */
            timezone?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoraryChartRequest
         * @description Request body for a KP horary chart.
         */
        HoraryChartRequest: {
            /**
             * Horary Number
             * @description KP horary number (1-249)
             */
            horary_number: number;
            /** Birth Lat */
            birth_lat: number;
            /** Birth Lon */
            birth_lon: number;
            /** Birth Location Name */
            birth_location_name?: string | null;
            /**
             * Query Note
             * @description The question being asked
             */
            query_note?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PaginatedResponse[ChartListItem] */
        PaginatedResponse_ChartListItem_: {
            /** Items */
            items: components["schemas"]["ChartListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description Register a new tenant + owner user in one step.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Tenant Slug
             * @description URL-safe slug for subdomain (e.g. 'astrojohn')
             */
            tenant_slug: string;
            /** Tenant Display Name */
            tenant_display_name: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Language */
            language?: string | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Language */
            language: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "super_admin" | "tenant_admin" | "astrologer" | "student" | "client_viewer";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_profile_api_v1_auth_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_natal_chart_api_v1_charts_natal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_horary_chart_api_v1_charts_horary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoraryChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_charts_api_v1_charts_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                client_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ChartListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_api_v1_charts__chart_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chart_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chart_api_v1_charts__chart_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chart_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                sort_by?: string;
                sort_order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_chart_api_v1_clients__client_id__chart_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
